version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    network_mode: "host"
#  node-exporter:
    #image: prom/node-exporter
    #image: nvme_exporter_v1:latest
#    build:
#      context: ./nvme_exporter
#      dockerfile: Dockerfile
#    ports:
#      - '9243:9243'
#    network_mode: "host"
  grafana:
    image: grafana/grafana
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
